version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      args:
        STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
        STRIPE_PRICE_ID: ${STRIPE_PRICE_ID}
        STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/appdb
        NEXT_PUBLIC_APP_URL: http://localhost:3000
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/appdb
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PRICE_ID: ${STRIPE_PRICE_ID}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_data: